/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ManagedAccountSchema extends BaseModel {
  static $columns = ['adminUserId', 'birthday', 'createdAt', 'cursorAccountActivated', 'cursorAccountActivatedAt', 'cursorPassword', 'cursorSheeridRequestSent', 'cursorSheeridRequestSentAt', 'id', 'mybcScreenshotHomeKey', 'mybcScreenshotProspectKey', 'mybcScreenshotRegistrationKey', 'outlookEmail', 'outlookEmailPassword', 'outlookFirstName', 'outlookLastName', 'schoolEmail', 'schoolEmailActivated', 'schoolEmailActivatedAt', 'schoolEmailPassword', 'schoolRequestSent', 'schoolRequestSentAt', 'studentId', 'updatedAt'] as const
  $columns = ManagedAccountSchema.$columns
  @column()
  declare adminUserId: number
  @column.date()
  declare birthday: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cursorAccountActivated: boolean
  @column.dateTime()
  declare cursorAccountActivatedAt: DateTime | null
  @column()
  declare cursorPassword: string | null
  @column()
  declare cursorSheeridRequestSent: boolean
  @column.dateTime()
  declare cursorSheeridRequestSentAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mybcScreenshotHomeKey: string | null
  @column()
  declare mybcScreenshotProspectKey: string | null
  @column()
  declare mybcScreenshotRegistrationKey: string | null
  @column()
  declare outlookEmail: string | null
  @column()
  declare outlookEmailPassword: string | null
  @column()
  declare outlookFirstName: string | null
  @column()
  declare outlookLastName: string | null
  @column()
  declare schoolEmail: string | null
  @column()
  declare schoolEmailActivated: boolean
  @column.dateTime()
  declare schoolEmailActivatedAt: DateTime | null
  @column()
  declare schoolEmailPassword: string | null
  @column()
  declare schoolRequestSent: boolean
  @column.dateTime()
  declare schoolRequestSentAt: DateTime | null
  @column()
  declare studentId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
